image: python:3.10

#variables:
#  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
#
#cache:
#  paths:
#    - .cache/pip
#    - venv/

#before_script:
#  - python --version  # For debugging
#  - pip install virtualenv
#  - virtualenv venv
#  - source venv/bin/activate

run:
  script:
    - python setup.py bdist_wheel
    # an alternative approach is to install and run:
    - pip install dist/*
    # run the command here
  artifacts:
    paths:
      - dist/*.whl

'.check':
  script:
    - export TOXENV="${CI_JOB_NAME##check}"
    - pip install tox
    - pip list
    - tox

'check py37':
  extends: '.check'
  image: 'python:3.7'

'check py38':
  extends: '.check'
  image: 'python:3.8'

'check py39':
  extends: '.check'
  image: 'python:3.9'

'check py310':
  extends: '.check'

'check cov310':
  extends: '.check'
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      - covhtml/*
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

'check mypy':
  extends: '.check'

'check flake8':
  extends: '.check'
  image: 'python:3.10'

'check pycodestyle':
  extends: '.check'

'check pydocstyle':
  extends: '.check'

#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc
#    - make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
