image: python:3.10

#variables:
#  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
#
#cache:
#  paths:
#    - .cache/pip
#    - venv/

#before_script:
#  - python --version  # For debugging
#  - pip install virtualenv
#  - virtualenv venv
#  - source venv/bin/activate

stages:
  - test
  - deploy

'.check':
  script:
    - export TOXENV="${CI_JOB_NAME##check}"
    - pip install tox
    - pip list
    - tox

'check py37':
  stage: test
  extends: '.check'
  image: 'python:3.7'

'check py38':
  stage: test
  extends: '.check'
  image: 'python:3.8'

'check py39':
  stage: test
  extends: '.check'
  image: 'python:3.9'

'check py310':
  stage: test
  extends: '.check'

'check cov310':
  stage: test
  extends: '.check'
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    paths:
      - covhtml/*
      - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

#'check mypy':
#  stage: test
#  extends: '.check'

'check flake8':
  stage: test
  extends: '.check'
  image: 'python:3.10'

'check pycodestyle':
  stage: test
  extends: '.check'

'check pydocstyle':
  stage: test
  extends: '.check'

pypi:
  stage: deploy
  script:
    - python -V
    - pip install twine wheel
    - pip list
    - python setup.py bdist bdist_wheel
    - twine upload dist/*
  only:
    - tags

#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc
#    - make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
