VERSION = '0.4.1'
PLUGINS2CLEAN = {
    "Abandoned_Flatv2_0.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Almalexia_Voicev1.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "FLG - Balmora's Underworld V1.1.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "BitterAndBlighted.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Building Up Uvirith's Legacy1.1.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Caldera.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "DD_Caldera_Expansion.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "NX9_Guards_Complete.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Radiant Gem.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Dwemer and Ebony Service Refusal.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Foyada Mamaea Overhaul.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Graphic Herbalism.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Graphic Herbalism - No Glow.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Graphic Herbalism Extra.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Hla Oad.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "CultSheog-1.02.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "CultSheog-TR1807.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Kilcunda's Balmora.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "MD_Azurian Isles.esm": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Magical Missions.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Mannequins for Sale.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Xenn's Marksman Overhaul.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Meteorite Ministry Palace - Higher.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "MW Containers Animated.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Go To Jail.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Go To Jail (Mournhold + Solshteim).ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "MRM.esm": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "NX9_Guards_Complete.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "OAAB - The Ashen Divide.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "On the Move.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Ports Of Vvardenfell V1.6.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Quill of Feyfolken 2.0.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Library of Vivec Overhaul - Full.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "SadrithMoraExpandedTR.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Sanctus Shrine.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "DA_Sobitur_Facility_Clean.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "DA_Sobitur_Quest_Part_1 Clean.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "DA_Sobitur_Quest_Part_2 Clean.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "DA_Sobitur_Repurposed_1.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "DA_Sobitur_TRIngred_Compat.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Stav_gnisis_minaret.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "OTR_Coast_Variety.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "TheForgottenShields - Artifacts_NG.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "SG-toughersixth.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Ttooth's Missing NPCs - No Nolus.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "True_Lights_And_Darkness_1.1.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "UCNature.esm": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "UFR_v3dot2_noRobe.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Vurt's BC Tree Replacer II.ESP": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Windows Glow - Bloodmoon Eng.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Windows Glow - Raven Rock Eng.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Windows Glow - Tribunal Eng.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
    "Windows Glow.esp": ['Morrowind.esm', 'Tribunal.esm', 'Bloodmoon.esm'],
}
TES3CMD = {
    'win32': {'0_37': 'tes3cmd-0.37v.exe',
              '0_40': 'tes3cmd-0.40-pre_rel2.exe'},
    'linux': {'0_37': 'tes3cmd-0.37w',
              '0_40': 'tes3cmd-0.40-pre_rel2'},
    'darwin': {'0_37': 'tes3cmd-0.37w',
               '0_40': 'tes3cmd-0.40-pre_rel2'},
}
