moht:
  api_ver: 0.7.0
  auto_save: false
tes3cmd_clean:
  clean_backup: true
  clean_cache: true
  data_files_dir: /home/emc/.wine/drive_c/GOG Games/Morrowind/Data Files
  mod_dir: /home/emc/clean/CitiesTowns/
  tes3cmd_bin: /home/emc/git/Modding-OpenMW/modhelpertool/moht/resources/tes3cmd-0.40-pre_rel2
  tes3cmd_ver: 40
